# Generated by Django 3.2.6 on 2021-08-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0007_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='random-stuff', max_length=225),
        ),
    ]
